background_opacity: 0.95
font:
  normal:
    family: UbuntuMono nerd font
  bold:
    family: UbuntuMono nerd font
  italic:
    family: UbuntuMono nerd font
  size: 9.5
colors:
  primary:
    background: '#0d0d0d'
    foreground: '#bbbbbb'
